name: Build Android AAB

on:
  push:
    branches:
      - main  # 你也可以用其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas whoami || eas login --token ${{ secrets.EAS_ACCESS_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Android AAB
        run: eas build --platform android --non-interactive --profile production
